name: jeffclaassen
favicon: null
layout_spectrum: 0.74085
typography_spectrum: 0.49759
title: Jeff Claassen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcf2'
    - '#db1b28'
    - '#fcb780'
    - '#100f1f'
    - '#e0695b'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
