name: jeffclaassen
favicon: null
layout_spectrum: 0.40559
typography_spectrum: 0.7447
title: Jeff Claassen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#aaecf6'
    - '#5ed5fc'
    - '#44b9fb'
    - '#bab4e5'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
