name: jeffclaassen
favicon: null
layout_spectrum: 0.41329
typography_spectrum: 0.49759
title: Jeff Claassen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090a0c'
    - '#ead8cf'
    - '#45cbd0'
    - '#0c5d7d'
    - '#e1b36d'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
