name: jeffclaassen
favicon: null
layout_spectrum: 0.5153594203293324
typography_spectrum: 0.9007195748854429
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9621771909296513
  lightness: 0.23532066657207906
  saturation: 0.8280406466219574
  rhythmicContrast: 0.5077843230683357
purpose: []
