name: jeffclaassen
favicon: null
layout_spectrum: 0.80433
typography_spectrum: 0.49759
title: Jeff Claassen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b8abc5'
    - '#5ab1ab'
    - '#f1e0ce'
    - '#615a57'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
